.TH koneetkiertoon-ETAYHTEYS "1" "September 13, 2011"
.SH "DESCRIPTION"
.LP 
Avaa etäyhteyden Koneet kiertoon asiakkaalta tukihenkilölle käyttäen SSH-tunnelia ja VNC:tä.
.SH "NAME"
.LP 
koneetkiertoon-etayhteys \- Avaa etäyhteyden Koneet kiertoon asiakkaalta tukihenkilölle käyttäen SSH-tunnelia ja VNC:tä.
.SH "SYNTAX"
.LP 
koneetkiertoon-etayhteys
.SH "OPTIONS"
.LP 

.SH "FILES"
.LP 
\fI/usr/bin/koneetkiertoon-etayhteys
.SH "AUTHORS"
.LP 
This manual page was written by Otto Kekäläinen <otto.kekalainen@linux-tuki.fi>,
for the Debian project (and may be used by others).
