.\" Linux-tuki.fi:n etäyhteys
.TH "linux-tuki-etayhteys" "1" "2.0.0" "Otto Kekäläinen <otto.kekalainen@linux-tuki.fi>" "1"
.SH "DESCRIPTION"
.LP 
Avaa etäyhteyden Linux-tuen asiakkaalta tukihenkilölle käyttäen SSH-tunnelia ja VNC:tä.
.SH "NAME"
.LP 
linux-tuki-etayhteys \- Avaa etäyhteyden Linux-tuen asiakkaalta tukihenkilölle käyttäen SSH-tunnelia ja VNC:tä.
.SH "SYNTAX"
.LP 
linux-tuki-etayhteys
.SH "OPTIONS"
.LP 

.SH "FILES"
.LP 
\fI/usr/bin/linux-tuki-etayhteys
.SH "AUTHORS"
.LP 
Otto Kekäläinen <otto.kekalainen@linux-tuki.fi>
